import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ToastContainer } from 'react-toastify';
import Container from "@mui/material/Container";
import ResponsiveAppBar from "@/components/Appbar";
import NextAuthProvider from "@/providers/NextAuthProvider";
import AxiosInterceptor from "@/providers/AxiosInterceptor";
import { SocketProvider } from "@/providers/SignalRProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ToastContainer />
          <NextAuthProvider>
            <ResponsiveAppBar />
            <Container sx={{ mt: 2 }}>
              <AxiosInterceptor >
                <SocketProvider>
                  {children}
                </SocketProvider>
              </AxiosInterceptor>
            </Container>
          </NextAuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html >
  );
}
